# Generated by Django 3.0.3 on 2020-02-28 10:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20200227_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
